plugin:
    name: 'lzaplata.gallery::lang.plugin.name'
    description: 'lzaplata.gallery::lang.plugin.description'
    author: 'Lukáš Záplata'
    icon: oc-icon-picture-o
    homepage: ''
permissions:
    default:
        tab: 'lzaplata.gallery::lang.plugin.name'
        label: 'lzaplata.gallery::lang.privilege.default'
    gallery_create:
        tab: 'lzaplata.gallery::lang.plugin.name'
        label: 'lzaplata.gallery::lang.privilege.gallery.create'
    gallery_delete:
        tab: 'lzaplata.gallery::lang.plugin.name'
        label: 'lzaplata.gallery::lang.privilege.gallery.delete'
navigation:
    main-menu-item:
        label: 'lzaplata.gallery::lang.plugin.name'
        url: lzaplata/gallery/galleries
        icon: icon-picture-o
        permissions:
            - default
