title: 'lzaplata.gallery::lang.plugin.name'
modelClass: LZaplata\Gallery\Models\Gallery
list: $/lzaplata/gallery/models/gallery/columns.yaml
recordUrl: 'lzaplata/gallery/galleries/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
