name: Gallery
modelClass: LZaplata\Gallery\Models\Gallery
form: $/lzaplata/gallery/models/gallery/fields.yaml
defaultRedirect: lzaplata/gallery/galleries
create:
    title: 'lzaplata.gallery::lang.create.title'
    redirect: 'lzaplata/gallery/galleries/update/:id'
    redirectClose: lzaplata/gallery/galleries
    flashSave: 'lzaplata.gallery::lang.create.flash'
update:
    title: 'lzaplata.gallery::lang.update.title'
    redirect: lzaplata/gallery/galleries
    redirectClose: lzaplata/gallery/galleries
    flashSave: 'lzaplata.gallery::lang.update.flash.update'
    flashDelete: 'lzaplata.gallery::lang.update.flash.delete'
preview:
    title: ffff
